name: python application
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
     
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt
      - name: 'Lint with flake8 run:| pip install flake8'
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
